meetup/config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
  resources :interests 
end

  resources :users

   root 'groups#index'

     get 'signup' => 'users#new' #, as: :purchase
     
     get 'login' => 'sessions#new' 
     post 'login' => 'sessions#create' 
     delete 'logout' => 'sessions#destroy'

     get 'start_group' => 'groups#new'
     post 'start_group' => 'groups#create'

     get 'start_event' => 'events#new'
     post 'start_event' => 'events#create'

     get 'join' => 'groups#join'
     get 'attend' => 'events#attend'

     get 'calender' =>'events#calender'
     
     get 'mycalender' =>'users#calender'
     get 'search' => 'users#search'

     post 'find' =>'groups#find'

     resources :comments
  resources :events do
  resources :comments end
     

end

meetup/app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :group
end

meetup/app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:interest, :group_id)
    end
end

meetup/app/helpers/interests_helper.rb
module InterestsHelper
end

meetup/app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

meetup/app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

meetup/app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interests</h1>

<table>
  <thead>
    <tr>
      <th>Interest</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.interest %></td>
        <td><%= interest.group %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

meetup/app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

meetup/app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interest:</strong>
  <%= @interest.interest %>
</p>

<p>
  <strong>Group:</strong>
  <%= @interest.group %>
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>