meetup/config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
  resources :interests 
end

  resources :users

   root 'groups#index'

     get 'signup' => 'users#new' #, as: :purchase
     
     get 'login' => 'sessions#new' 
     post 'login' => 'sessions#create' 
     delete 'logout' => 'sessions#destroy'

     get 'start_group' => 'groups#new'
     post 'start_group' => 'groups#create'

     get 'start_event' => 'events#new'
     post 'start_event' => 'events#create'

     get 'join' => 'groups#join'
     get 'attend' => 'events#attend'

     get 'calender' =>'events#calender'
     
     get 'mycalender' =>'users#calender'
     get 'search' => 'users#search'

     post 'find' =>'groups#find'

     resources :comments
  resources :events do
  resources :comments end
     

end

meetup/app/models/group.rb
class Group < ActiveRecord::Base

has_many :events
has_many :interests
has_many :members
has_many :users, :through => :members
geocoded_by :name, :latitude => :lat , :longitude => :lang

belongs_to :user

has_attached_file :g_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
validates_attachment_content_type :g_image, :content_type => /\Aimage\/.*\Z/


validates :name, :location , :description , :MembersName, :g_image , presence: true
end

meetup/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  def join
    @group = Group.find(params[:group_id])
    @member = Member.new(:user_id => params[:user_id], :group_id => params[:group_id])
    @member.save
    redirect_to @group
  end

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
    group_id=params[:id]
    @num_members= Member.where(:group_id => group_id).count
    if logged_in?
      user_id=current_user.id
      @member = Member.find_by(user_id: user_id ,:group_id => group_id )
      if @member
        @flag_join=0
      else 
        @flag_join=1
      end
    else
      @flag_join=0  
    end  
    @group = Group.find(group_id)
    @events = (Event.where(:group_id => group_id)).order("date") 
  end

  # GET /groups/new
  def new
     @flag=0 
    if logged_in?
      @group = Group.new
    else
      flash[:danger] = 'Please Login first'
      redirect_to login_path
    end  
  end

  # GET /groups/1/edit
  def edit
    @flag=1
  end



def create 
  puts  "***********************************"
  puts  params[:lat]
  puts  params[:lang] 
  puts  "***********************************"
  @group = Group.new(group_params) 
  @inter = Interest.new(interest_params) 

  group_id=Group.last.id 
  
  array = @inter['interest'].split(/, /)
    array.size.times do |i|
    @interst_group=Interest.new(:group_id=> group_id,:interest=> array[i])
    @interst_group.save
  end 

  
   if @group.save 
    redirect_to @group 
  else render 'new' 
  end 
end



  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    # delete event
    Event.where(:group_id => @group.id).destroy_all
    # delete members
    Member.where(:group_id => @group.id).destroy_all
    Interest.where(:group_id => @group.id).destroy_all
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def find
  
  @interest = params[:interest];
  @search_options =  params[:option];
  @search_text =  params[:search_text];
  if ! ['any'].include?(@interest)
      @interests  = Interest.select('group_id').where("interest = ? ", @interest );
      if @interests.length >= 1       
        groups_ids = Array.new
        @interests.each do |title|
          groups_ids.push(title.group_id)
        end
        if ['1', '3', '5'].include?(@search_options)
          @groups = Group.near([params[:lat], params[:long]], @search_options).where("id in (?) ", groups_ids );
        else
          @groups = Group.where("id in (?) ", groups_ids );
        end  
      else 
        @groups = Group.near([params[:lat], params[:long]], @search_options).where("name like ?", '%'+@search_text+'%')  
      end  
  elsif ['1', '3', '5'].include?(@search_options)
    @groups = Group.near([params[:lat], params[:long]], @search_options).where("name like ?", '%'+@search_text+'%')
  else
    @groups = Group.where("name like ?", '%'+@search_text+'%')
  end 
  render partial: "find";
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :location, :user_id, :g_image , :description , :MembersName , :lat ,:lang)
    end

    def interest_params
      params.require(:interest).permit(:interest) 
    end
end

meetup/app/helpers/groups_helper.rb
module GroupsHelper
end

meetup/app/views/groups/_find.html.erb
 <% @groups.each do |group| %>
        <div class="col-sm-6 col-md-4">

            <div class="thumbnail">
                <div class="page-header">
                    <h3 class="text-primary"><%= group.name  %></h3>
                </div>
                <%= link_to group do %>
                  <%= image_tag group.g_image.url , style: "width:300px;height:300px;" %>
                <% end %>
              
            </div>

        </div>
    <% end %>

meetup/app/views/groups/_form.html.erb
<style type="text/css" media="screen">
.container{
margin-left: 550px;
width:500px;

}

fieldset { width: 320px; margin-top: 20px}
fieldset strong { display: block; margin: 0.5em 0 0em; }
fieldset input { width: 95%; }

ul span { color: #999; }



body {
  color: #333;
}

body, input, button {
  line-height: 1.4;
  font: 13px Helvetica,arial,freesans,clean,sans-serif;
}


a {
  color: #4183C4;
  text-decoration: none;
}

#examples a {
  text-decoration: underline;
}

#geocomplete { width: 200px}

.map_canvas { 
  width: 600px; 
  height: 400px; 
  margin: 10px 20px 10px 0;
}

#multiple li { 
  cursor: pointer; 
  text-decoration: underline; 
}

#error_explanation {
  color: red;
  background-color: white;
  border: white;
}

.field_with_errors {
    background-color: white;
}
</style>

<div class="container">
    <% if @flag==0  %>
  <h1 class="page-header text-primary">Create Group</h1>
  <% end %>
  <% if @flag==1  %>
  <h1 class="page-header text-primary">Edit</h1>
  <% end %>
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@group.errors.count, "error") %>.
          <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    </div>

  </div>
<% end %>

  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, id:"location", class: 'form-control' %>
  </div>


  <div class="form-group">
    
    <%= fields_for :interest do |t| %>
       <%= t.label :interest %>
       <br>
       <%= t.text_field :interest, id:"interest" ,value:"", class: 'form-control', placeholder: "Pick up to 15 topics" %>
    </br>
    <input type="button" id="art" class="btn btn-info" value="Art" name="Art" />
    <input type="button" id="food" class="btn btn-info" value="Food" name="Food" />  
    <input type="button" id="fun" class="btn btn-info" value="Fun" name="Fun" />
    <input type="button" id="computer" class="btn btn-info" value="Computer" name="Computer" /> 
    <br><br>
    <input type="button" id="science" class="btn btn-info" value="Science" name="Science" /> 
    <% end %>  
  </div>


  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder:"Enter Group Name"%>
  </div>


  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control', class: 'form-control', placeholder:"Enter Group Description"%>
  </div>

 <div class="form-group">
    <%= f.label :MambersName %><br>
    <%= f.text_field :MembersName, class: 'form-control', placeholder:"Enter MambersName"%>
  </div> 

 <div class="form-group">
   <%= f.label :image %><br>
  <%= f.file_field :g_image %>
</div>

<div >
  <%= f.hidden_field :user_id, value:current_user.id %>
  <%= f.hidden_field :lang, id:"lang" %>
  <%= f.hidden_field :lat, id:"lat" %>
</div>

  <div class="actions">
    <%= f.submit :submit , class: "btn btn-primary" %>
  </div>
<% end %>
</div>

<script>



$( "#geocomplete" ).focusout (function() {
  
  var geocoder2 = new google.maps.Geocoder();
  var address = document.getElementById("geocomplete").value;
  geocoder2.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK)
    {
      var lat = results[0].geometry.location.A ;
      var lng = results[0].geometry.location.F;
    }
  });

});


$( "#location" ).focusout(function() {

  var geocoder2 = new google.maps.Geocoder();
  var address = document.getElementById("location").value;
  geocoder2.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK)
    {
      var lat = results[0].geometry.location.A ;
      var lng = results[0].geometry.location.F;
      
      document.getElementById("lang").value = lng; 
      document.getElementById("lat").value = lat; 
    }
  });

});

    var str = "" ;
    $( "#art" ).click(function() {
        var value = $( "#art" ).val()+", ";
        $( "#art" ).hide();
        str = str + value
        document.getElementById('interest').value = str;
      
    });

    $( "#food" ).click(function() {
        var value = $( "#food" ).val()+", ";
        $( "#food" ).hide();
        str = str + value
        document.getElementById('interest').value = str;
        
    });

    $( "#fun" ).click(function() {
        var value = $( "#fun" ).val()+", ";
        $( "#fun" ).hide();
        str = str + value
        document.getElementById('interest').value = str;
        
    });

    $( "#computer" ).click(function() {
    var value = $( "#computer" ).val()+", ";
    $( "#computer" ).hide();
    str = str + value
    document.getElementById('interest').value = str;
        
    });

    $( "#science" ).click(function() {
    var value = $( "#science" ).val()+", ";
    $( "#science" ).hide();
    str = str + value
    document.getElementById('interest').value = str;
        
     });

</script>


<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<%= javascript_include_tag "geocomplete" %> 

<script>

  var geocoder;
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(successFunction, errorFunction);
} 
//Get the latitude and the longitude;
function successFunction(position) {

    var lat = position.coords.latitude;
    var lng = position.coords.longitude;
    console.log("lat = "+ lat);
    console.log("lang = "+ lng);
      document.getElementById("lang").value = lng; 
      document.getElementById("lat").value = lat; 

    codeLatLng(lat, lng)
}

function errorFunction(){
    alert("Geocoder failed");
}
geocoder = new google.maps.Geocoder();
  function codeLatLng(lat, lng) {

    var latlng = new google.maps.LatLng(lat, lng);
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
     
        if (results[1]) {

            for (var i=0; i<results[0].address_components.length; i++) {
            for (var b=0;b<results[0].address_components[i].types.length;b++) {


                if (results[0].address_components[i].types[b] == "administrative_area_level_1") {
                    city= results[0].address_components[i];
                    break;
                }

                if (results[0].address_components[i].types[b] == "country") {
                    country= results[0].address_components[i];
                    break;
                }
            }
        }

        document.getElementById("location").value = city.short_name+","+country.short_name;
        $("#location").geocomplete(); 
       

        } else {
       
        }
      } else {
        
      }
    });
  }
</script>

meetup/app/views/groups/edit.html.erb
<%= render 'form' %>

meetup/app/views/groups/index.html.erb
<div class="container-fluid"  style="padding-left: 0px; padding-right:0px;  margin:0px;padding:0px;">
  <div class="jumbotron" style="background-image: url('<%= asset_path( '4.jpg' ) %>');width: 100%;
    height: 600px;
    background-repeat: no-repeat;
    background-origin: center center;
    background-size: cover; padding-left: 0px; padding-right: 0px; margin-left:0px;margin-right:0px; margin:0px ; padding:0px">
  </div>

</div>


<div class="container">

      <%= csrf_meta_tag %> 
      <!--Search bar  -->
      <div class="bs-example" data-example-id="navbar-form">
          <nav class="navbar navbar-default">
              <div class="container-fluid">

                  <div class="navbar-header">
               
                      <button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-2" data-toggle="collapse" type="button"></button>

              </div>
              <div id="bs-example-navbar-collapse-2" class="collapse navbar-collapse">
            
                  <div class="navbar-form navbar-left" role="search">
                      <div class="form-group">
                     
                        <select id="interest" name="interest" class="form-control" >
                            <option value="any">any</option>
                            <option value="Science">Science</option>
                            <option value="Fun">Fun</option>
                            <option value="Food">Food</option>
                            <option value="Art">Art</option>
                            <option value="Computer">Computer</option>
                        </select>

                    
                        
                          <input id="search_text" name="search_text" type="text" placeholder="Find meetups" value="" placeholder="Search" class="form-control"/>
                        


                          <input id="geocomplete" name="geocomplete" type="text" placeholder="Type in an address" value="" placeholder="Search" class="form-control"/>
                          

                        <!-- drop down of miles  -->
                      <div class="form-group">
                        <select id="option" name="option" class="form-control">
                            <option   value="1">1 mile</option>
                            <option value="3">3 miles</option>
                            <option value="5">5 miles</option>
                            <option value="any distance">any distance</option>
                            <input type="hidden" name="long" id ="long"/>
                            <input type="hidden" name="lat" id ="lat"/>
                        </select>
                      </div>

                        <!-- end of drop down of miles  -->
                      <button type="button" class="btn btn-default" id="btn">Serach</button>  
                      </div>
                      
                  </div>
                  <div class="pull-right"> 
                      <%= link_to 'My Calender', mycalender_path , class: "navbar-btn btn btn-default " %>
                      </div>

              </div>
        
          </div>
          
      </nav>
      </div>
      <!--End Search bar  -->

</div>

<div class="container">

  <p id="notice"><%= notice %></p>


<!-- case normal user and is logged and if any userdisplay site without logging -->
<% if logged_in? and current_user.is_admin == false  or !logged_in?%>

  <div id="result" class="row">
    <% @groups.each do |group| %>
        <div class="col-sm-6 col-md-4">

            <div class="thumbnail">
                <div class="page-header">
                    <h3 class="text-primary"><%= group.name  %></h3>
                </div>
                <%= link_to group do %>
                  <%= image_tag group.g_image.url , style: "width:300px;height:300px;" %>
                <% end %>
              
            </div>

        </div>
    <% end %>
  </div>

<% else %>
<!-- case Admin user and is logged  -->
<%= link_to 'Create Group', new_group_path %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th text-align="center">Group Image</th>
          <th text-align="center">Group Name </th>
          <th text-align="center">Group Description</th>
          <th text-align="center">Group Location</th>
          <th text-align="center">Show</th>
          <th text-align="center">Edit</th>
          <th text-align="center">Delete</th>

        </tr>
      </thead>
      <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td text-align="center"><%= image_tag group.g_image.url(:thumb) , class: "thumbnail" %></td>
          <td text-align="center"><strong><%= group.name %></strong></td>
          <td text-align="center"><%= group.description %></td>
          <td text-align="center"><%= group.location %></td>
          <td><%= link_to 'Show', group , class:"btn btn-primary" %></td>
           <td><%= link_to 'Edit', edit_group_path(group),class:"btn btn-default" %></td>
           <td> <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
          
        </tr>
        <% end %>
    </table>


 <% end %> 
</div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<%= javascript_include_tag "geocomplete" %>  

<script type="text/javascript"> 


$( "#geocomplete" ).focusout (function() {
  
  var geocoder2 = new google.maps.Geocoder();
  var address = document.getElementById("geocomplete").value;
  geocoder2.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK)
    {
      var lat = results[0].geometry.location.A ;
      var lng = results[0].geometry.location.F;
      document.getElementById("lat").value = lat;
      document.getElementById("long").value = lng;
    }
  });

});

$( "#btn" ).click(function() {
  
      var lat = document.getElementById("lat").value;
      var lng = document.getElementById("long").value;
      var option = document.getElementById("option").value;
      var search_text = document.getElementById("search_text").value;
      var interest = document.getElementById("interest").value;
      var posting = $.post( "find", { long: lng , lat: lat , option: option, search_text: search_text ,interest: interest   } );
            
      posting.done(function( data ) {
           $("#result").html(data);
      });


});


var geocoder;

if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(successFunction, errorFunction);
} 

function successFunction(position) {

  var lat = position.coords.latitude;
  var lng = position.coords.longitude;
  document.getElementById("long").value = lng; 
  document.getElementById("lat").value = lat;    
  codeLatLng(lat, lng)
}

function errorFunction(){
  alert("Geocoder failed");
}
geocoder = new google.maps.Geocoder();
function codeLatLng(lat, lng) {

  var latlng = new google.maps.LatLng(lat, lng);
  geocoder.geocode({'latLng': latlng}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      //console.log(results)
      if (results[1]) {

        for (var i=0; i<results[0].address_components.length; i++) {
          for (var b=0;b<results[0].address_components[i].types.length;b++) {

            if (results[0].address_components[i].types[b] == "administrative_area_level_1") {
              city=results[0].address_components[i];
              break;
            }

            if (results[0].address_components[i].types[b] == "country"  || results[0].address_components[i].types[b] == "administrative_area_level_2"  ) {
              country= results[0].address_components[i];
              break;
            }
          }
        }
        document.getElementById("geocomplete").value =city.short_name+","+country.short_name;
        $("#geocomplete").geocomplete(); 
        

      } else {
        
      }
    } else {
      
    }
  });
}
</script> 

<script>

    $( "#search_text" ).focus(function(){
      openSelect('#interest');
      // $( "#interest" ).show();
    })
</script>

meetup/app/views/groups/new.html.erb
<%= @group_id  %>

<%= render 'form' %>

meetup/app/views/groups/show.html.erb
<div class="container" >
	<div class="page-header">
		<h1  class="text-primary"><%= @group.name %></h1>
	</div>
	<div class="raw">
		<div class="col-md-3">
		<br><br>
			<img src="<%= @group.g_image %>" class="img-rounded" style="width:200px ; height:200px;">
			<br><br><br>
			<ul class="list-group">
				  <li class="list-group-item">Members<span class="badge"><%= @num_members %></span></li>
				
				<% if logged_in? and current_user.id != @group.user_id  %>				  
					<% if @flag_join==1 %>
				  		<li class="list-group-item">
						Join Group
						<span class="pull-right">
							<%= link_to 'Join', {:controller => "groups", :action => "join", :user_id => current_user.id, :group_id => @group.id }, class:"btn btn-success" %>
							</span>
						</div>
						
			   		  </li>
					<% end %>
				<% end %>	



				<% if logged_in? %>
					<% if @group.user_id==current_user.id %>
						<li class="list-group-item">Create Event

						<%= link_to 'Create Event', {:controller => "events", :action => "new", :group_id => @group.id }, class:"btn btn-primary" %> </li>

						<li class="list-group-item">Edit Group Info
							<%= link_to 'Edit', edit_group_path(@group),class:"btn btn-warning" %>
            			</li>
            			<li class="list-group-item">Delete Group	
            				<%= link_to 'Destroy', @group, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %>
            			</li>
					<% end %>
				<% end %>	

				
			</ul>
			
		</div>

		<div class="col-md-9">
			<div class="page-header">
				<h4>Group Description :</h4>
				
			</div>
			<p> <%= @group.description %> </p>
			<div class="page-header">

				<h4>Event Listing</h4>
			</div>
			<% @events.each do |event| %>
				
				<div class="well well-lg"> 
					<div class="raw">
						<div class="col-md-2">
							<%= image_tag event.ev_image.url, style: "height:50px; width:100px;"  %>	
						</div>
							 <h5><strong><%= link_to event.name, event %></strong></h5>
						<small>  <strong><%= event.date %> </strong></small>	
				
					</div>
						
						
				</div>	
			<% end %>
		</div>

	</div>
	

</div>
</div>