meetup/config/routes.rb
Rails.application.routes.draw do
  
  resources :groups do
  resources :interests 
end

  resources :users

   root 'groups#index'

     get 'signup' => 'users#new' #, as: :purchase
     
     get 'login' => 'sessions#new' 
     post 'login' => 'sessions#create' 
     delete 'logout' => 'sessions#destroy'

     get 'start_group' => 'groups#new'
     post 'start_group' => 'groups#create'

     get 'start_event' => 'events#new'
     post 'start_event' => 'events#create'

     get 'join' => 'groups#join'
     get 'attend' => 'events#attend'

     get 'calender' =>'events#calender'
     
     get 'mycalender' =>'users#calender'
     get 'search' => 'users#search'

     post 'find' =>'groups#find'

     resources :comments
  resources :events do
  resources :comments end
     

end

meetup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>
<!-- addmin case -->

<% if logged_in? and current_user.is_admin == true %>
  <nav class="navbar navbar-default"> 
    <div class="container-fluid">
      <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="  #bs-example-navbar-collapse-1"> 
              <span class="sr-only">Toggle navigation</span> 
            </button> 
         
           </div>  
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> 

            <ul class="nav navbar-nav"> 
              <li class="active"><%= link_to 'Groups', root_url %></li> 
              <li><%= link_to 'Users', users_path %></li> 
              <li><%= link_to 'Events', events_path %></li>
              <li><%= link_to 'Comments', comments_path %></li>  
            </ul> 


            <ul class="nav navbar-nav navbar-right">

               <% if !logged_in? %>
                  <li><%= link_to 'Signup', signup_path %></li>
                  <li><%= link_to 'Login', login_path %></li> 
               <% end %> 
               <% if logged_in? %> 
                 <li><%= link_to current_user do %> 
                        <strong>welcome <%= current_user.name %></strong>
                        <%= image_tag current_user.image.url(:thumb), class: "img-circle"%>
                      <% end %>
                 </li>
                 <li><%= link_to 'Logout', logout_path, method: "delete" %></li> 
              <% end %>
            </ul>
        </div> 
    </div>
  </nav>


<% else %>
<!-- user case -->





<nav class="navbar navbar-default" >
  <div class="container-fluid ">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="#" style="font-size:30px; coloe:black;"> </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
          <li class="active" style="margin-left:30px;" >
            <%= link_to 'Groups', root_url %>
          </li>
          
          <li style="margin-left:30px;"><%= link_to 'Create Group', new_group_path %>
          </li>
      </ul>
         
      <ul class="nav navbar-nav navbar-right">

          <% if !logged_in? %>
            <li style="margin-left:30px;" >
                <%= link_to 'Signup', signup_path %>
            </li>
            
            <li style="margin-left:30px;">
                <%= link_to 'Login', login_path %>
            </li>
          <% end %>
          <% if logged_in? %>
             <li>
                 <%= link_to current_user do %>
                     <strong>welcome <%= current_user.name %></strong>

                 <% end %>
             </li>
             <li>  <%= image_tag current_user.image.url(:thumb), class: "img-circle" , style: "height:50px; width:50px"%> </li>
            <li><%= link_to 'Logout', logout_path, method: "delete" %></li>
          <% end %>
     
      </ul>
    </div>
  </div>
</nav>


   

   </div>
<% end %>

<%= yield %>



</body>
</html>